### ISSUE TITLE
Silent Sign-In Failure and Inadequate Error Reporting (Android)

### ISSUE THREAD

**Issue by oremlawi** [Abedalkareem/games_services#187]
The games_services Flutter library fails to report Google Play Games sign-in errors properly. GamesServices.signIn() doesn't always throw errors when sign-in fails, and the returned AuthenticationResult often lacks useful error messages, making debugging difficult. This leads to misleading "success" messages and hinders reliable integration.

Logs:
```
I/PlayService(12290): isAuthenticated: false toString: com.google.android.gms.games.AuthenticationResult@1e8e499
I/signin  (12290): success
```

**Comment by theLee3** [comment]
Are you using the published version or the dev branch from GitHub?

**Comment by oremlawi** [comment]
Same here @AnruStander, iPhone works perfectly, Android suffers although we've tried to start the entire configuration many times on different **Google Cloud** projects!

@theLee3 I'm trying this but not working, any idea?

```
games_services:
  git:
    url: https://github.com/Abedalkareem/games_services.git
    ref: develop
    path: packages/games_services # with and without
```

Error message:
Could not find a file named "packages/games_services/pubspec.yaml" in https://github.com/Abedalkareem/games_services.git 06be38adc9cf35a6fe1e67e9f6e629a6e174d831.
