### ISSUE TITLE
On fresh install, first authentication fails, but will succeed on the second app open.

### ISSUE THREAD

**Issue by gnarhard** [Abedalkareem/games_services#188]
Flutter v3.24.3
games_services: using develop branch

Seems to be working properly on the stable release.

**Comment by theLee3** [comment]
Android or iOS?

**Comment by gnarhard** [comment]
I was experiencing it on iOS. Didn't check android.

**Comment by theLee3** [comment]
I am unable to replicate the behavior on iOS. Can you share the code for your auth flow? Are you seeing an error, or are you just not seeing auth succeeding?

**Comment by theLee3** [comment]
Thanks for the quick response. I will implement a similar flow and find the issue.

**Comment by gnarhard** [comment]
My pleasure! Thank you for all of your hard work on this package.

**Comment by theLee3** [comment]
Please try the patch out.

```yaml
games_services:
    git:
      url: https://github.com/Abedalkareem/games_services.git
      ref: bugfix/back-compat
      path: games_services
```
